name: fuck-shit-up

on: [push, pull_request]

# on:
#   push:
#     branches:
#       - master
#       - main

jobs:
  fuck-shit-up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Sup bruh
        run: |
          echo "sup bruh"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Test AWS privileges
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
        run: |
          ./get_ssm_value.sh
